[package]
name = "la-term"
version = "0.0.0"
edition = "2021"

# Library for hash tables.
[dependencies.hashbrown]
version = "~0.11.2"

# Property-based testing.
[dev-dependencies.proptest]
default-features = false
features = ["alloc"]
version = "^1.0.0"
