[package]
name = "la-term"
version = "0.0.0"
edition = "2021"

# Library for hash tables.
[dependencies.hashbrown]
version = "~0.11.2"

[dependencies.num-bigint]
default-features = false
version = "~0.4.3"
