"name": "CI"

"on":

  "push":

    "branches":
      - "trunk"

    "pull_requests":
      - "trunk"

"jobs":

  "build":

    "runs-on": "ubuntu-latest"

    "env":
      "RUSTFLAGS": "--deny warnings"

    "steps":

      - "uses": "actions/checkout@v2.4.0"

      - "uses": "cachix/install-nix-action@v15"

      - "name": "Install Nix dependencies"
        "run": "nix-shell --keep RUSTFLAGS --pure --run true"

      - "name": "Build Rust crates (dev profile)"
        "run": "nix-shell --keep RUSTFLAGS --pure --run 'cargo build --profile dev'"

      - "name": "Test Rust crates (dev profile)"
        "run": "nix-shell --keep RUSTFLAGS --pure --run 'cargo test --profile dev'"

      - "name": "Build Rust crates (release profile)"
        "run": "nix-shell --keep RUSTFLAGS --pure --run 'cargo build --profile release'"

      - "name": "Test Rust crates (release profile)"
        "run": "nix-shell --keep RUSTFLAGS --pure --run 'cargo test --profile release'"

      - "name": "Build Rust docs"
        "run": "nix-shell --keep RUSTFLAGS --pure --run 'cargo doc'"
